language: csharp
solution: BusylightRestHost.sln
mono:
  - latest
  - 5.4.1
install:
  - nuget restore BusylightRestHost.sln
script:
  - msbuild BusylightRestHost.Tests/BusylightRestHost.Tests.csproj
  - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe BusylightRestHost.Tests/BusylightRestHost.Tests.csproj