language: csharp
solution: BusylightRestHost.sln

mono:
- 5.4.1
install:
- nuget restore BusylightRestHost.sln

script:
- echo ${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER} > BusylightRestHost/Resources/version && cat BusylightRestHost/Resources/version
- msbuild BusylightRestHost.Tests/BusylightRestHost.Tests.csproj
- mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe BusylightRestHost.Tests/BusylightRestHost.Tests.csproj
- msbuild /p:Configuration=Release BusylightRestHost.sln /p:TargetFrameworkVersion=v4.7 /target:BusylightRestHost
- sha1sum BusylightRestHost/bin/Release/BusylightRestHost.exe > BusylightRestHost/bin/Release/BusylightRestHost.exe.sha1
  
deploy:
  provider: releases
  api_key:
    secure: bImI+ot6iJu34KxGCFitw9vqQdu6dVh8n4SFACRwM5ukWzrEbYf3IiyhQ354hoidbHvMQ2WAe3zVWAFMcepLvjmhVLMjcaPvZP6G8JWs4YyXZNPWJ5kmbP8hBxyLerHVPPyfnvQfd1XggVJ6ENgeqyZpvmY9/NdbjfFY0Xfr20Px4HC7Ql9OfIvGssru/A48OFsJ5WRxqdWAvMx4XUmkdV257I2F4W+br8OnF7Z7MxYLGgjhZE9jU/yG52KYZGrjdJrTIUt3jffegW1/bAjO2Z2iLeYzDKDcZ4SbwHC0JdHkY1GEPlXgogf/hYjoCyjGzDocCSQbdoBVYxTUEqtHsqmy3VzJJ97gjuzCjG6NiK7ioz/pZinLbI9QMtzQtGdpRkAMSqLgixurjkHzYcsVNhUSAg6yhG1DHbMeum31IVSle2QhmRRGm47A1G6RgJlY7qWMrCzC/NEWhjYBh8w77XgcYWb8nubctklbv0M4wfsIwb0BGcXEsFZ0+Xd/cEHKE8GMop2QCfRB3ybniTmfp4ViEU6XBZ+/t/V4wGD3ghnoOWfqHJjb4kxHexkmYPxuYeK1gOieITzL4aM3cfxH1sv5HJ28K1NmabgKzYxTj8RG0BBfnFVASVyeEUI3EuZm3J7iYOfTA62B+XPTzKwhRPC/iRuIQAxjzcdUGqF2cx8=
  file: 
    - BusylightRestHost/bin/Release/BusylightRestHost.exe
    - BusylightRestHost/bin/Release/BusylightRestHost.exe.sha1
  skip_cleanup: true
  on:
    repo: thuliumcc/busylight-rest-host
    tags: true
