language: csharp
solution: BusylightRestHost.sln
mono:
  - latest
  - 5.4.1
install:
  - nuget restore BusylightRestHost.sln
script:
  - msbuild /p:Configuration=Release BusylightRestHost.sln /p:TargetFrameworkVersion=v4.7 /target:BusylightRestHost
  - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe BusylightRestHost.Tests/BusylightRestHost.Tests.csproj